In [17]:
%%time
N = ord('M') % 15 + 1
print(N)

3
CPU times: total: 0 ns
Wall time: 181 μs


## Завдання №1

In [99]:
import numpy as np
import time

def task1_numpy(n):
    return np.diag(np.arange(1, n+1))

def task1_iter(n):
    A = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(i+1 if i == j else 0)
        A.append(row)
    return np.array(A, dtype=int)

In [100]:
%%time
print(task1_iter(5), "\n")

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]] 

CPU times: total: 0 ns
Wall time: 330 μs


## Завдання №3

In [118]:
import numpy as np
import time

def task3_numpy(n, m, r, c):
    A = np.ones((n, m), dtype=int)
    A[::r, :] = 0
    A[:, ::c] = 0
    return A

def task3_iter(n, m, r, c):
    A = []
    for i in range(n):
        row = []
        for j in range(m):
            if i % r == 0 or j % c == 0:
                row.append(0)
            else:
                row.append(1)
        A.append(row)
    return np.array(A)

In [120]:
%%time
print(task3_numpy(6, 7, 2, 3), "\n")

[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]] 

CPU times: total: 0 ns
Wall time: 638 μs


## Завдання №6

In [130]:
import numpy as np
import time

def task6_numpy(arr):
    arr = np.array(arr, dtype=int)
    arr[arr != 0] = -1
    return arr

def task6_iter(arr):
    return [1 if x != 0 else 0 for x in arr]

In [131]:
%%time
arr = [3,4,0,9,7,0,6,0,4,0,3]
print("Task 6:", task6_iter(arr), "\n")

Task 6: [1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1] 

CPU times: total: 0 ns
Wall time: 101 μs


## Завдання №7

In [22]:
import numpy as np
import time

def task7_numpy(arr):
    arr = np.array(arr, dtype=int)
    arr[arr == 0] = -1
    return arr

def task7_iter(arr):
    return [-1 if x == 0 else x for x in arr]

In [23]:
%%time
arr7 = [3,4,0,6,5,0,3,0,4]
print("Завдання 7:", task7_numpy(arr7), "\n")

Завдання 7: [ 3  4 -1  6  5 -1  3 -1  4] 

CPU times: total: 0 ns
Wall time: 302 μs


## Завдання №8

In [137]:
import numpy as np
import time

def task8_numpy(arr):
    arr = np.array(arr)
    zeros = np.sum(arr == 0)
    nonzeros = np.sum(arr != 0)
    return zeros, nonzeros

def task8_iter(arr):
    zeros = sum(1 for x in arr if x == 0)
    nonzeros = sum(1 for x in arr if x != 0)
    return zeros, nonzeros

In [144]:
%%time
arr8 = [3,4,0,9,8,2,4,0,8,4,1]
zeros, nonzeros = task8_numpy(arr8)
print(f"Нулів: {zeros}")
print(f"Не нулів: {nonzeros}")

Нулів: 2
Не нулів: 9
CPU times: total: 0 ns
Wall time: 436 μs


## Завдання №11

In [147]:
import numpy as np
import time

def task11_numpy(n):
    A = np.ones((n, n), dtype=int)
    B = np.zeros((n + 2, n + 2), dtype=int)
    B[1:-1, 1:-1] = A
    return B

def task11_iter(n):
    B = []
    for i in range(n + 2):
        row = []
        for j in range(n + 2):
            if i == 0 or i == n + 1 or j == 0 or j == n + 1:
                row.append(0)
            else:
                row.append(1)
        B.append(row)
    return B


In [153]:
%%time
matrix = task11_numpy(4)
for row in matrix:
    print(row)

[0 0 0 0 0 0]
[0 1 1 1 1 0]
[0 1 1 1 1 0]
[0 1 1 1 1 0]
[0 1 1 1 1 0]
[0 0 0 0 0 0]
CPU times: total: 0 ns
Wall time: 470 μs


## Завдання №16

In [154]:
import numpy as np
import time

def task16_numpy(n):
    A = np.arange(n + 1)
    mask = (A > n/4) & (A < 3*n/4)
    A[mask] = 0
    return A

def task16_iter(n):
    A = []
    for x in range(n + 1):
        if n/4 < x < 3*n/4:
            A.append(0)
        else:
            A.append(x)
    return A

In [157]:
%%time
print("Task 16:", task16_iter(10), "\n")

Task 16: [0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10] 

CPU times: total: 0 ns
Wall time: 105 μs


## Завдання №18

In [169]:
import numpy as np
import time

def task18_numpy(n):
    arr = np.random.randint(0, 99, size=n)
    unique_count = np.unique(arr).size
    return arr, unique_count

def task18_iter(n):
    arr = [np.random.randint(0, 99) for _ in range(n)]
    unique_count = len(set(arr))
    return arr, unique_count

In [180]:
%%time
np.random.seed(151)
n = 30
arr, unique_count = task18_iter(n)
print("В послідовності", arr, "-", unique_count, "унікальних чисел")

В послідовності [24, 90, 93, 44, 71, 74, 85, 32, 34, 75, 50, 91, 71, 69, 31, 39, 76, 36, 82, 88, 57, 74, 39, 58, 78, 88, 6, 51, 4, 70] - 26 унікальних чисел
CPU times: total: 0 ns
Wall time: 637 μs


## Завдання №19

In [181]:
import numpy as np

def task19_numpy(n):
    arr = np.linspace(0, 1, n+2)[1:-1]
    return np.round(arr, 3)

def task19_iter(n):
    step = 1 / (n + 1)
    arr = [round(step * (i+1), 3) for i in range(n)]
    return arr

In [185]:
%%time
n = 10
print(task19_iter(n))

[0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]
CPU times: total: 0 ns
Wall time: 1.29 ms


## -------------------------------------------------------------------------------------------------------

## Завдання 2

In [16]:
import numpy as np

np.set_printoptions(precision=8, suppress=True)

# Матриця A і вектор b (система 4x4)
# Система (в порядку рядків):
# x1  + 2x2  + 3x3 - 2x4 = 6
# x1  -  x2  - 2x3 - 3x4 = 8
# 3x1 + 2x2  -  x3 + 2x4 = 4
# 2x1 - 3x2  + 2x3 +  x4 = -8

A = np.array([
    [1,  2,  3, -2],
    [1, -1, -2, -3],
    [3,  2, -1,  2],
    [2, -3,  2,  1]
], dtype=float)

b = np.array([6, 8, 4, -8], dtype=float)

n = A.shape[0]
assert A.shape == (4,4) and b.shape == (4,)

print("Матриця A:")
print(A)
print("\nВектор b:")
print(b)

# Розв'язок за Крамером
detA = np.linalg.det(A)
print(f"\ndet(A) = {detA:.8f}")

if abs(detA) < 1e-12:
    raise ValueError("Матриця A сингулярна або близька до сингулярної: формули Крамера не застосовні.")

# Обчислюємо детермінанти замінних матриць
x_cramer = np.zeros(n, dtype=float)
det_list = []
for i in range(n):
    Ai = A.copy()
    Ai[:, i] = b            # замінюємо i стовпець на b
    detAi = np.linalg.det(Ai)
    det_list.append(detAi)
    x_cramer[i] = detAi / detA

print("\nДетермінанти для замінних матриць (det A_i):")
for i, d in enumerate(det_list, start=1):
    print(f" det A_{i} = {d:.8f}")
print("\nРозв'язок за формулами Крамера (x_cramer):")
print(x_cramer)

# Перевірка a матричним множенням A через крамер
Ax_cramer = A @ x_cramer
residual_cramer = Ax_cramer - b
print("\nПеревірка (A @ x_cramer):")
print("A @ x_cramer =", Ax_cramer)
print("Різниця (A @ x_cramer - b) =", residual_cramer)

# Перевірка b через обернену матрицю A^-1 через b
A_inv = np.linalg.inv(A)
x_inv = A_inv @ b
residual_inv = A @ x_inv - b

print("\nРозв'язок через обернену матрицю (x_inv = A^{-1} @ b):")
print(x_inv)
print("Різниця (A @ x_inv - b) =", residual_inv)

# Перевірка c numpy.linalg.solve
x_solve = np.linalg.solve(A, b)
residual_solve = A @ x_solve - b

print("\nРозв'язок через numpy.linalg.solve (x_solve):")
print(x_solve)
print("Різниця (A @ x_solve - b) =", residual_solve)

# Порівняння рішень через numpy.allclose()
print("\n- ПОРІВНЯННЯ -")
print("Cramer == inv :", np.allclose(x_cramer, x_inv))
print("Cramer == solve:", np.allclose(x_cramer, x_solve))
print("inv == solve  :", np.allclose(x_inv, x_solve))

# Чисельна оцінка
def vec_info(name, x):
    print(f"\n{name}:")
    print(x)
    print(" ||A@x - b|| (inf-norm) =", np.max(np.abs(A @ x - b)))
    print(" ||A@x - b|| (2-norm)   =", np.linalg.norm(A @ x - b))

vec_info("x_cramer", x_cramer)
vec_info("x_inv", x_inv)
vec_info("x_solve", x_solve)

# Округлимо рішення до зручного вигляду 8 знаків
print("\nОкруглені рішення (8 знаків):")
print("x_cramer :", np.round(x_cramer, 8))
print("x_inv    :", np.round(x_inv, 8))
print("x_solve  :", np.round(x_solve, 8))


Матриця A:
[[ 1.  2.  3. -2.]
 [ 1. -1. -2. -3.]
 [ 3.  2. -1.  2.]
 [ 2. -3.  2.  1.]]

Вектор b:
[ 6.  8.  4. -8.]

det(A) = 288.00000000

Детермінанти для замінних матриць (det A_i):
 det A_1 = 324.00000000
 det A_2 = 558.00000000
 det A_3 = -324.00000000
 det A_4 = -630.00000000

Розв'язок за формулами Крамера (x_cramer):
[ 1.125   1.9375 -1.125  -2.1875]

Перевірка (A @ x_cramer):
A @ x_cramer = [ 6.  8.  4. -8.]
Різниця (A @ x_cramer - b) = [ 0. -0. -0. -0.]

Розв'язок через обернену матрицю (x_inv = A^{-1} @ b):
[ 1.125   1.9375 -1.125  -2.1875]
Різниця (A @ x_inv - b) = [0. 0. 0. 0.]

Розв'язок через numpy.linalg.solve (x_solve):
[ 1.125   1.9375 -1.125  -2.1875]
Різниця (A @ x_solve - b) = [-0.  0. -0.  0.]

- ПОРІВНЯННЯ -
Cramer == inv : True
Cramer == solve: True
inv == solve  : True

x_cramer:
[ 1.125   1.9375 -1.125  -2.1875]
 ||A@x - b|| (inf-norm) = 3.552713678800501e-15
 ||A@x - b|| (2-norm)   = 5.197930934883577e-15

x_inv:
[ 1.125   1.9375 -1.125  -2.1875]
 ||A@x - b|

## -------------------------------------------------------------------------------------------------------

## Завдання 3

In [11]:
import numpy as np
import time
import pprint

# Матриці A і B
A_np = np.array([[4, 5, -2],
                 [3, -1, 0],
                 [-1, 0, 7]], dtype=float)

B_np = np.array([[2, 1, -1],
                 [0, 1, 3],
                 [5, 7, 3]], dtype=float)

# Те ж у вигляді списків списків для ітеративного підходу (доробити)
A_list = A_np.tolist()
B_list = B_np.tolist()

# Кількість повторів для вимірювання часу
REPS = 100000
# a NumPy-реалізація
def numpy_expr(A, B):
    # Обчислюємо 3A - (A - 2B)
    return 3*A - (A - 2*B)
    # (альтернативно: return 2*(A + B))

# b1 Ітеративно: через list comprehension
def listcomp_expr(A, B):
    # A та B - списки списків однакового розміру
    m = len(A)
    n = len(A[0])
    return [[int(3*A[i][j] - (A[i][j] - 2*B[i][j])) for j in range(n)] for i in range(m)]

# (b2) Ітеративно явні цикли
def loops_expr(A, B):
    m = len(A)
    n = len(A[0])
    # Нульова матриця результату
    R = [[0]*n for _ in range(m)]
    for i in range(m):
        for j in range(n):
            # обчислення елемента
            R[i][j] = int(3*A[i][j] - (A[i][j] - 2*B[i][j]))
    return R

# Вимір часу
def time_func(fn, *args, reps=100000):
    # Викликаємо fn(*args) повторно reps разів і повертаємо час та останній результат
    t0 = time.perf_counter()
    res = None
    for _ in range(reps):
        res = fn(*args)
    t1 = time.perf_counter()
    return t1 - t0, res

# Виконання
# NumPy (перший виклик для розігріву за яким виключаємо одноразовый overhead)
_ = numpy_expr(A_np, B_np)

t_np, res_np = time_func(numpy_expr, A_np, B_np, reps=REPS)
# Перетворимо результат у цілі для наочного порівняння
res_np_int = res_np.astype(int)

# List comprehension
t_lc, res_lc = time_func(listcomp_expr, A_list, B_list, reps=REPS)

# Явні цикли
t_loops, res_loops = time_func(loops_expr, A_list, B_list, reps=REPS)

In [14]:
print("Матриця A:")
pprint.pprint(A_list)
print("\nМатриця B:")
pprint.pprint(B_list)

print("\nРезультати обчислення (один прикладний результат)")
print("NumPy result (int):")
print(res_np_int)          # numpy array

print("\nList-comp result:")
pprint.pprint(res_lc)      # list of lists

print("\nLoops result:")
pprint.pprint(res_loops)   # list of lists

# Перевірки рівності через numpy.allclose
res_lc_np = np.array(res_lc, dtype=float)
res_loops_np = np.array(res_loops, dtype=float)

print("\nПеревірка рівності через numpy.allclose()")
print("NumPy vs List comprehension:", np.allclose(res_np_int, res_lc_np))
print("NumPy vs Loops             :", np.allclose(res_np_int, res_loops_np))
print("List comp vs Loops         :", np.allclose(res_lc_np, res_loops_np))

# Вимірювання часу
print("\nЧаси виконання (повний час, сек)")
print(f"NumPy ({REPS} повторів): {t_np:.6f} s  (середнє {t_np/REPS*1e6:.3f} μs/виклик)")
print(f"List comprehension ({REPS} повторів): {t_lc:.6f} s  (середнє {t_lc/REPS*1e6:.3f} μs/виклик)")
print(f"Loops ({REPS} повторів): {t_loops:.6f} s  (середнє {t_loops/REPS*1e6:.3f} μs/виклик)")

Матриця A:
[[4.0, 5.0, -2.0], [3.0, -1.0, 0.0], [-1.0, 0.0, 7.0]]

Матриця B:
[[2.0, 1.0, -1.0], [0.0, 1.0, 3.0], [5.0, 7.0, 3.0]]

Результати обчислення (один прикладний результат)
NumPy result (int):
[[12 12 -6]
 [ 6  0  6]
 [ 8 14 20]]

List-comp result:
[[12, 12, -6], [6, 0, 6], [8, 14, 20]]

Loops result:
[[12, 12, -6], [6, 0, 6], [8, 14, 20]]

Перевірка рівності через numpy.allclose()
NumPy vs List comprehension: True
NumPy vs Loops             : True
List comp vs Loops         : True

Часи виконання (повний час, сек)
NumPy (100000 повторів): 0.499244 s  (середнє 4.992 μs/виклик)
List comprehension (100000 повторів): 0.204975 s  (середнє 2.050 μs/виклик)
Loops (100000 повторів): 0.270430 s  (середнє 2.704 μs/виклик)
